### ISSUE TITLE
user password

### ISSUE THREAD

**Issue by funtomas** [Offerel/SyncMarks-Webapp#17]
what is defalt username and passsword or how can i set it?

**Comment by Offerel** [comment]
You can use the credentials from the initDB function:

admin / mypass

You can change the initial credentials also in this function, if you want, or later after logging in.

**Comment by funtomas** [comment]
9. 10. 2020, 17:00:45 - Info: Initiate PHP startup sync
29. 10. 2020, 17:00:45 - Info: Get list of clients.
29. 10. 2020, 17:00:45 - Info: Get notifications for current client.
29. 10. 2020, 17:00:45 - Info: Sending parameters to server (client, action): 196a6c94-5c42-4191-a79e-ff0730ebc6c9, startup
29. 10. 2020, 17:00:48 - Info: This browser seems to be a new client for the server. The client is now registered at the server. No bookmarks are imported. You can import them manually.
29. 10. 2020, 17:00:48 - Info: List of clients retrieved successfully.
29. 10. 2020, 17:08:21 - Info: Link successfully send., Client: 196a6c94-5c42-4191-a79e-ff0730ebc6c9
29. 10. 2020, 17:08:23 - Info: Link successfully send.
29. 10. 2020, 17:10:43 - Info: Requesting all local bookmarks for export
29. 10. 2020, 17:10:43 - Info: Export finalized.
29. 10. 2020, 17:10:43 - Info: Sending export of local bookmarks for client 196a6c94-5c42-4191-a79e-ff0730ebc6c9
29. 10. 2020, 17:10:44 - Error: There was a problem exporting the bookmarks. Syntax error, malformed JSON

**Comment by Offerel** [comment]
The error message has nothing todo with user or password. The login was ok. The string "Syntax error, malformed JSON" is the response from the import function. Can you please open a new issue for this? 

Please add information which browser you are using for exporting and if some none standard bookmarks are saved in your bookmarks folders. For example bookmarklets or other "not-http(s)-urls". If you use such bookmarks, please send me an example of such a bookmark.
