### ISSUE TITLE
Nearly empty home page

### ISSUE THREAD

**Issue by kayceegb** [Offerel/SyncMarks-Webapp#18]
Hello,

I'm having problem to make webapp work properly. I mean, after some fix in the code, I am able to login, with default credentials, but after that, I think there are missing parts somewhere. 

I attached a screenshot. I think there should be at least, the default bookmark visible, plus some menus. 

The fix is just for database creation. 
--- a/index.php
+++ b/index.php
@@ -1670,7 +1670,7 @@ function doLogin($database,$realm) {

 function initDB($database) {
        if(!file_exists(dirname($database))) {
-               if(!mkdir(dirname($database,0777,true))) {
+               if(!mkdir(dirname($database),0777,true)) {
                        e_log(1,"Directory for database couldn't created, please check privileges");
                }
                else {

I have this problem with different browsers. I'm stuck with this for a moment now and don't really understand what's happening. 
Any idea maybe ? 

Thx

**Comment by kayceegb** [comment]
I can't edit the issue and I don't see the screenshot
So it is here https://ibb.co/th8m9RP

**Comment by Offerel** [comment]
Is the database and the tables created at the given path?
Is the database initialized, meaning filled with initial data?
Are the privileges correct for that folder, so that the webserver/php user has write privileges to the database path and config file path?

**Comment by kayceegb** [comment]
With the fix mentionned above, the database is created and populated. Access to config file seems good, as webserver's logs show a need for a second fix (typo bug) with sender var and I'm able to increase webapp's log verbosity too. 

It's just after initial login I can't do anything. Moving over the top left 3 dots or clicking them does nothing, idem for "add new bookmark". Cliking the search icon opens the search field but nothing happens after. 

Attached there are logs for webserver and webapp. 

Is it possible to have a screen with the expected result after initial login ?

**Comment by kayceegb** [comment]
Same as above, I can't see the attached file and can't edit
So it is here https://pastebin.com/raw/Q5yfMnxM

**Comment by Offerel** [comment]
There was an issue, when the user has no client registered for his account, which is the case, when no addon was connected before. I have fixed this in the last commit at the dev branch.

Additionally i have found an error in db initializing sequence. I insert now a folder and additionally a bookmark with correct id format. This is also included in the mentioned commit [41e8b33](https://github.com/Offerel/SyncMarks-Webapp/commit/41e8b33a532257ceea940783628338113725b9ee)

**Comment by kayceegb** [comment]
Yesterday after trying all I had in my pocket, I started some "random" testing and was successful in having something working. 
Like you said, and that was my conclusion yesterday, if there is no client registered, nearly nothing happens. At this level I think at least adding a bookmark should be possible. 
When I connected the addon and exported the bookmarks in ff profile, the webapp, after a refresh, was able to show the tree. 

I'm in a test process for now, so I should be able to try the last commit. I will tell you later.

**Comment by Offerel** [comment]
Yep. Thats it. If no client was registered, the Javascript failed and prevents all JS functions after that error. Thats why no menu was working. This should be now fixed with the commit. 

Adding bookmarks without any clients should now work also, because of the DB initialization change. Many thx for reporting that error.

**Comment by kayceegb** [comment]
That's better now. After initial login, there is a Menu folder and a bookmark in that folder. Menu's are working too (3 dots, add, search). 

I saw one thing. I do not know if it is desirable or not. When you create a bookmark, via webapp, and you don't select a folder, the bookmark is created in the Menu folder. 

Once you connect the addon and export ff bookmarks, that overwrites what was in the webapp. This one I don't know if it should be noticed here on in the addon page. 

I have other fixes and ideas. I like the combo addon/webapp, I'll stick with this for a moment I think.

**Comment by Offerel** [comment]
Yes, if you export from the browser, everything at the server for this user is overwritten. That's why I display a warning at first export from browser. I can't remember, if there is a notification in the webapp.

Creating a bookmark defaults to this folder. Only when you specify a folder, its written to the selected folder. So you can't get lost in bookmarks created in random folders. 

If you have ideas, please open an issue for the idea. Maybe I can implement it.

**Comment by kayceegb** [comment]
Thanks for the informations.

I don't know for the notification in the webapp, but there is no message at export time in the addon about the overwrite (at import time there is a message). At least in the version from amo. I think I will open an issue for this at addon repo. 

For webapp I will start with easy ones ;)

**Comment by Offerel** [comment]
BTW: Since desktop browsers save bookmarks with unknown folder per default in "Other Bookmarks", i have changed this now in DB initialization also to this folder with commit [4a8eaf6](https://github.com/Offerel/SyncMarks-Webapp/commit/4a8eaf6a758d0f0a4a50b23fd2cd4e4c567ecc79)
