### ISSUE TITLE
Missing config.inc.php

### ISSUE THREAD

**Issue by kayceegb** [Offerel/SyncMarks-Webapp#19]
Hello,

Following the instructions from installation page I have this message.

PHP Warning:  include_once(/var/www/html/bmsync/config.inc.php): failed to open stream: No such file or directory

There is a config.inc.php.dist file. 

Is it user's responsability to create config.inc.php or copy config.inc.php.dist to config.inc.php ? So informations from installation page are wrong. 

K.

**Comment by Offerel** [comment]
I have changed the installation instruction, to reflect this.
