### ISSUE TITLE
Syntax error, unexpected end of file

### ISSUE THREAD

**Issue by kayceegb** [Offerel/SyncMarks-Webapp#20]
Hi,

Following instructions from installation page + copy config.inc.php.dist to config.inc.php, I have the following message:

PHP Parse error:  syntax error, unexpected end of file, expecting variable (T_VARIABLE) or ${ (T_DOLLAR_OPEN_CURLY_BRACES) or {$ (T_CURLY_OPEN)

After this little fix, before the copy, it's seems ok

> diff --git a/config.inc.php.dist b/config.inc.php.dist
> index f9655f7..1085f05 100644
> --- a/config.inc.php.dist
> +++ b/config.inc.php.dist
> @@ -3,5 +3,5 @@ $database = __DIR__.'/database/bookmarks.db';
>  $logfile = "/var/log/bookmark.log";
>  $realm = "Bookmarks";
>  $loglevel = 2;
> -$sender = "bookmarks@yourdomain.com;
> -?>
> \ No newline at end of file
> +$sender = "bookmarks@yourdomain.com";
> +?>

K,

**Comment by Offerel** [comment]
Fixed with commit [6bdcc39](https://github.com/Offerel/SyncMarks-Webapp/commit/6bdcc39c6916c62fae33bcf8a455381a184592b5)
