### ISSUE TITLE
dirname() expects at most 2 parameters, 3 given

### ISSUE THREAD

**Issue by kayceegb** [Offerel/SyncMarks-Webapp#21]
Hi, 

When following instructions from installation page + fix from https://github.com/Offerel/SyncMarks-Webapp/issues/20 + copy config.inc.php.dist to config.inc.php, I have the following messages:

* dirname() expects at most 2 parameters, 3 given
* mkdir(): Invalid argument
* Directory for database couldn't created, please check privileges

I was able to correct this with this change:
> diff --git a/index.php b/index.php
> index 0f4b0a1..422263a 100644
> --- a/index.php
> +++ b/index.php
> @@ -1675,7 +1675,7 @@ function doLogin($database,$realm) {
> 
>  function initDB($database) {
>         if(!file_exists(dirname($database))) {
> -               if(!mkdir(dirname($database,0777,true))) {
> +               if(!mkdir(dirname($database),0777,true)) {
>                         e_log(1,"Directory for database couldn't created, please check privileges");
>                 }
>                 else {

After that db is created, populated and I can login. 

K.

**Comment by kayceegb** [comment]
I'll try to put patch in a different way

    diff --git a/index.php b/index.php
    index 0f4b0a1..422263a 100644
    --- a/index.php
    +++ b/index.php
    @@ -1675,7 +1675,7 @@ function doLogin($database,$realm) {
    
     function initDB($database) {
            if(!file_exists(dirname($database))) {
    -               if(!mkdir(dirname($database,0777,true))) {
    +               if(!mkdir(dirname($database),0777,true)) {
                            e_log(1,"Directory for database couldn't created, please check privileges");
                    }
                    else {

I hope this one works.

**Comment by Offerel** [comment]
Fixed with commit [9da4518](https://github.com/Offerel/SyncMarks-Webapp/commit/9da45182c5153951ef25df8a010ed25afc99e178)
