### ISSUE TITLE
Allow search by url

### ISSUE THREAD

**Issue by kayceegb** [Offerel/SyncMarks-Webapp#23]
Hi,

A little improvement.

For now, when you filter BMs via search function, the lookup is done only on bmTitle.

That would bo good if the lookup can also be done on bmurl. There are cases where you have in head a search pattern for url and not for page title. 

K.

**Comment by Offerel** [comment]
added with commit [662776c](https://github.com/Offerel/SyncMarks-Webapp/commit/662776cfc86f4acd9526f26320a58907c7dec29b)
