### ISSUE TITLE
Allow bookmark removal

### ISSUE THREAD

**Issue by kayceegb** [Offerel/SyncMarks-Webapp#24]
Hi,

There is a add bookmark option but no bookmark delete option. 

Can this be implemented ? 

K.

**Comment by Offerel** [comment]
Try right click on a bookmark...

**Comment by kayceegb** [comment]
It is not working but there 2 different cases. 
Sometimes, right clicking bookmark opens ff context menu, like with folder where it opens ff context menu always.
And other case, it opens nothing. From browser console, it reports:
    TypeError: e.srcElement is undefined

**Comment by Offerel** [comment]
Currently there is only a contextmenu, if you rightclick a bookmark. If you rightclick a folder, the browser context is opened.

**Comment by kayceegb** [comment]
You are right. Trying with vivaldi, I can see the context menu with move, delete, ... 

In ff, I can't see it. Maybe it is related to the version I use. I have 60esr. I know it is old but it is linked to my workflow. My interest for SyncMarks is to let me upgrade FF later, once I have validated I can make it correspond to my needs.

**Comment by Offerel** [comment]
This should work also with FF 60. Maybe some caching issue. Ff is sometimes a little bit confused with caches, specially when a js library is used. At least with currently ff nightly it works.

**Comment by kayceegb** [comment]
Hummm. I have done a "clear all history", followed by a force refresh, without success. Even a new fresh ff profile does not help. 
I will retry with a newer ff version after I have upgraded. 

I note the option is already there. 

And to finish the full message from browser console is:
    TypeError: e.srcElement is undefined bookmarks.min.js:9:3415

Thanks for your time :)

**Comment by Offerel** [comment]
Maybe FF60 misses some standard JS attributes in this old version. Can you please test with FF version > 65? If this isn't fixed there, we must find an other way. But since its working here and no standard JS things have changed the last time, it should work.

**Comment by Offerel** [comment]
Can you please try commit [4c59672](https://github.com/Offerel/SyncMarks-Webapp/commit/4c596720f9a881fd02b270622d1dcf0fefdf3d9d) with your FF60ESR if that works better?

**Comment by kayceegb** [comment]
It's a lot better. 

While testing I lost it after some time :/ but a refresh helped to restore it.
