### ISSUE TITLE
Option for folder creation

### ISSUE THREAD

**Issue by kayceegb** [Offerel/SyncMarks-Webapp#25]
Hi,

We can create bookmarks directly from the webapp but not folders. 

I think it would be great to have this, so we can class BM at creation time. 

What do you think about that ? 

K.

**Comment by Offerel** [comment]
I know, this is missing. I will work on this. Just give me some time to found a reliable way.

**Comment by kayceegb** [comment]
No problem. This is not very high priority. ;)

**Comment by Offerel** [comment]
partially added with commit [ba36fea](https://github.com/Offerel/SyncMarks-Webapp/commit/ba36fea7992e744d04d0c3c3e68e57147f8b838f). You can reach this via context menu, if you rightclick a bookmark (not folder). I must add additional changes, to make it work the way i want it, But folder will be created successfully as of now.

**Comment by kayceegb** [comment]
I see preliminary work ^^

I was able to create a folder too. But, I don't know if you are already aware about that, it's not possible to move a BM to the newly created folder. In other folder, the move is ok. 

About option position, I had in head something more with "Add new bookmark", I don't know if it is that your are thinking about. 

And as I said above, this one is not high priority. It could be considered as a postit for later. I added some issues in addon. I think there are more critical than this one ;)

**Comment by Offerel** [comment]
I have tried to reproduce the issue with moving the bookmark, but cant reproduce that.

Regarding the "Add new bookmark" button. I had planned to remove this button completely and use only the conext menu for all operations. Thats why i added the folder creation option there.

**Comment by kayceegb** [comment]
Sad to read that you want to remove the "Add new bookmark" button. In my opinion it have a good place where it is now. Completing it with folder creation there seems logic to me. The decision is yours.

**Comment by Offerel** [comment]
I can leave the button there. I have no personal preferences where it is located. But I would leave the creation of a directory in the context menu, because you can select the parent folder directly.

**Comment by kayceegb** [comment]
I see what you mean for directory creation. It is a valid option. 

For bookmark creation do you want to use the bookmark context menu ? Or are you going to use a folder context menu ? 

In my opinion, bookmark creation/folder creation should be kept together at the same location.

**Comment by Offerel** [comment]
I tend to keep the button at the bottom, for fast creation of a bookmark. Additionally, i can think of adding a "create bookmark" entry in an context menu. I will also add a separate context menu on folders. This isn't added as of yet.
