### ISSUE TITLE
malformed json when trying to export to addon

### ISSUE THREAD

**Issue by kayceegb** [Offerel/SyncMarks-Webapp#26]
Hi,

I'm not sure if it should go here or to addon page as that works with dav mode. 

So tried to export my real BMs, and not just a sample bookmarks, that ended with a malform json. Playing a little with this, I identied that when there is a "%22" pattern in url or title, that does not work. With just "%2" it's ok. 

K.

**Comment by Offerel** [comment]
Do you have access to your database and can tell me, whats the url for this entry, saved in the db?
You can use the query `select * from bookmarks where bmURL like '%duckduckgo.com%';`

I will try, if i can escape the quotes before i export them. I'm a little bit confused, if there are 2 quotes or only one.

**Comment by Offerel** [comment]
I think, i got it.

**Comment by kayceegb** [comment]
Yes there 2 double-quotes. In this example, it's a search engine search for exact pattern, here mysearch: https://duckduckgo.com/?q="mysearch"

Are you talking about request to syncmarks's db ? There's no entry for the request. That seems logic, export failed. 

And I have trouble to locate url in FF's db

**Comment by kayceegb** [comment]
I think I found it. In moz_places there is this entry
    1119|https://duckduckgo.com/?q=%22mysearch%22||moc.ogkcudkcud.|0|0|0|-1||RneqtyDyGabW|1|47357548680833||

Hope that helps

**Comment by Offerel** [comment]
Fixed with commit [d9f4b03](https://github.com/Offerel/SyncMarks-Webapp/commit/d9f4b03e022a144d90ed591b1de1c92f97e0802a)

**Comment by kayceegb** [comment]
Funny to see your fix. Since this morning, I continue my tests, and was able to fix this the same way you did it. 
I was able to import my BMs after that(~600 BMs) with success.

I have also applied the same fix for addmark and that was also working. Not posted this because I thought both were a little bit ugly. Do you want me to create another issue for addmark ?

**Comment by Offerel** [comment]
Feel free, but meanwhile i have added the change also for this function in the latest commit. If you want to open a issue for this, please close it and link it to this issue here.
