### ISSUE TITLE
Folders created in browser are not created in webapp

### ISSUE THREAD

**Issue by kayceegb** [Offerel/SyncMarks-Webapp#29]
Hi,

Folders created in bowser, at least FF, are not created in webapp.

First case was for a folder created in an empty folder. That failed. (Fixed)(at the end of https://github.com/Offerel/SyncMarks-Extension/issues/20 with https://github.com/Offerel/SyncMarks-Webapp/commit/3c31b9ccd82bd890ecfd99e7beed7ff35ef20882)
Second case is for a folder creation in a folder that already have a folder. 

K.

**Comment by kayceegb** [comment]
About https://github.com/Offerel/SyncMarks-Webapp/commit/5fc0654ac367df0b6695098308c14f88fbbf0c19, I have done the same modification on my side. Just I left the part about userid to prevent that an ID already exists for another user.

**Comment by Offerel** [comment]
You are right, added this now in commit [b42acb0](https://github.com/Offerel/SyncMarks-Webapp/commit/b42acb07941d498f3a48e0c2ea556be79edeb591)
