### ISSUE TITLE
Unable to sync after creation of existing bookmark in another folder

### ISSUE THREAD

**Issue by kayceegb** [Offerel/SyncMarks-Webapp#32]
Hi,

I found this one also. 
I have a bookmark in one folder (here unfiled/other bookmark) and trying to add the same bookmark in another folder, here menu/bookmarks menu. Sync fails and here are the logs

```
==> /var/log/bookmark.log <==
[02-Dec-2020 15:10:26] - [debug] - admin@shared.ff - 127.0.0.1 - SELECT * FROM `users` WHERE `userName`='admin@shared.ff'
[02-Dec-2020 15:10:26] - [notice] - admin@shared.ff - 127.0.0.1 - Get userdata from the database
[02-Dec-2020 15:10:26] - [debug] - admin@shared.ff - 127.0.0.1 - SELECT * FROM `users` WHERE `userName`='admin@shared.ff'
[02-Dec-2020 15:10:26] - [notice] - admin@shared.ff - 127.0.0.1 - Try to add folder '"azerty" at DuckDuckGo'
[02-Dec-2020 15:10:26] - [debug] - admin@shared.ff - 127.0.0.1 - {"id":"FSt_9PYG1J57","url":"https://duckduckgo.com/?q=%22azerty%22&ia=web","title":"\"azerty\" at DuckDuckGo","type":"bookmark","folder":"menu________","nfolder":"Bookmarks Menu","added":1606921825988}
[02-Dec-2020 15:10:26] - [notice] - admin@shared.ff - 127.0.0.1 - Check if bookmark already exists for user.
[02-Dec-2020 15:10:26] - [debug] - admin@shared.ff - 127.0.0.1 - SELECT COUNT(*) AS bmcount, MAX(bmAction) as bmaction FROM `bookmarks` WHERE `bmUrl` = 'https://duckduckgo.com/?q=&#34;azerty&#34;&ia=web' and userID = 1
[02-Dec-2020 15:10:26] - [notice] - admin@shared.ff - 127.0.0.1 - Bookmark not added, it exists already for this user
```

K.

**Comment by Offerel** [comment]
Unfortunately this is by design. Since I can't trust the ID's from the browser, the only chance to identify a bookmark is by compare the url or to have at least unique URLs.

That's why there is no fix until the api will change.

Compare folder and url takes to long.

**Comment by kayceegb** [comment]
Well, it seems as I am able to mitigate this a little. 

```
diff --git a/index.php b/index.php
index 500db7b..ca0d282 100644
--- a/index.php
+++ b/index.php
@@ -946,7 +946,7 @@ function addBookmark($database, $ud, $bm) {
    $db = new PDO('sqlite:'.$database);
    $db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    e_log(8,"Check if bookmark already exists for user.");
-   $query = "SELECT COUNT(*) AS bmcount, MAX(bmAction) as bmaction FROM `bookmarks` WHERE `bmUrl` = '".$bm['url']."' and userID = ".$ud["userID"];
+   $query = "SELECT COUNT(*) AS bmcount, MAX(bmAction) as bmaction FROM `bookmarks` WHERE `bmUrl` = '".$bm['url']."' and userID = ".$ud["userID"]." AND `bmParentID` = '".$bm['folder']."'";
    e_log(9,$query);
    $statement = $db->prepare($query);
    $statement->execute();
@@ -1807,4 +1807,4 @@ function initDB($database,$suser,$spwd) {
    }
    $db = NULL;
 }
-?>
\ No newline at end of file
+?>
```

First bookmark is created via ctrl-d which defaults to "Other bookmarks" folder. Second bookmark is created via tab's context menu "Bookmark tab" which defaults to "Bookmarks Menu". With the modification above, the second bookmark is created in the correct folder and display well in webapp. 

What do you think about that ? What about the reliability ?

**Comment by Offerel** [comment]
I see what you mean. The problem is, that there can be situations, where you call this function really often. In that case the query becomes really slow. At least in my environment. Additionally, it doesn't make sense to add the same bookmark multiple times. Personally i think there is no real useful benefit.

**Comment by kayceegb** [comment]
I have a 10 years old laptop as main computer with his original spining hdd. I have not seen a lot of difference with or without the modification in export or sync operations. In term of performance that should be negligeable in my opinion. 

As of the use case, for example, I have a workflow where I open different tabs in a window and do some navigation about a subject, then save all bookmarks at once in a folder. Later, I can come to the subject again, with different approach, and sometime have the same urls and save those new bookmarks again in another folder. All these bookmarks are "linked" each other. If I loose a bookmark, it's like there is some information missing. Then reopen one or the other folder all at once. 

It is something possible in FF, I have a need for that and I think I'm not the only one.

**Comment by Offerel** [comment]
With the current api this will lead to corrupted bookmarks, duplicates or accidentally removed bookmarks. Additionally it tends to break a parallel sync with internal browser sync. That's why i will not implement this.

**Comment by kayceegb** [comment]
Corrupted ? I don't see how. Maybe a bookmark edit ? That should be mitigable with limiting the edit search to folder's level compared to global level. 

Duplicates ? For sure. This is the idea. Once again, that  should allow duplicates at global level but not at folder level which is already not possible in browser. 

Accidentally removed ? Browser already asks if you want to remove the count of duplicates if there are duplicates. So that should be in phase with browser. 

I do not use internal browser sync. What is exactly broke ? Duplicates ?
