### ISSUE TITLE
Default credentials place

### ISSUE THREAD

**Issue by kayceegb** [Offerel/SyncMarks-Webapp#34]
Hi, 

I see you have moved recently, the default credentials created at db initialization, to config.inc.php.dist.

I my opinion they should not be there. It's not like these credentials are for connection, by the backend, to a db or directory. 

The documentation already say that after first connection, user should change password and userid if necessary (options which are available from webapp). 

So, default credentials should be removed from config.inc... and reverted back to index.php as a db initialization informations. 
And documentation should be updated with default credentials at point 4. 

K.

**Comment by Offerel** [comment]
No, they will stay there. This are only used for db initialization and wont be used later. That's why this is the right place for them.

**Comment by kayceegb** [comment]
Yes they are used only as db initialisation, that's why it's strange to find them there.
