### ISSUE TITLE
Request for getting folder when adding bookmark

### ISSUE THREAD

**Issue by kayceegb** [Offerel/SyncMarks-Webapp#46]
Hi,

The query for retrieving folder is
>     $query = "SELECT `bmID` FROM `bookmarks` WHERE `bmID` = '".$bm["folder"]."' AND `userID` = ".$ud['userID']." UNION ALL SELECT 'unfiled_____' WHERE NOT EXISTS (SELECT 1 FROM `bookmarks` WHERE `bmID` = '".$bm["folder"]."');";

Shouldn't there be a userID in the where not exists part ? 

K.

**Comment by Offerel** [comment]
No, this isn't needed there.
