### ISSUE TITLE
Support for special bookmarks

### ISSUE THREAD

**Issue by kayceegb** [Offerel/SyncMarks-Webapp#51]
Hi,

I see in some place that you exclude some bookmarks from being added/imported/exported. What is the reason for that ? 

I have a patch that enables some of these special bookmarks to be added/imported/exported to/from backend. 

I think it would be a good point to support that as browser supports them and for those who have some of these bookmarks, that would allow safer futur operations. 

K.

**Comment by Offerel** [comment]
I only want to support standard bookmarks, certainly not special niche ones.

**Comment by kayceegb** [comment]
It's not really a big change but adds at least support for separators, about:blank and about:private bookmarks. 

But as you want.
