### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by johmor52** [Offerel/SyncMarks-Webapp#61]
I have one problem. After install I can't open the menu. The button change but nothing happens when I click on it.
It worked on 1.2.17, but not in the new version. Installed in a map at my homesite.
I have tried in Linux also with php7.3, but the same result. At homesite php 7.1 and other versions.
Hope for a solution. It's a good work so far...

**Comment by Offerel** [comment]
I cant reproduce this, but maybe there is a error message in the webconsole of your browser? You can reach that by pressing F12 and look for "Console". Sometimes such errors occur when old content is loaded from the cache. You can try to reload the page after you clear the cache of the browser or you can try to reload the page and ignore the cache. To do this, you can reload a page by pressing CTRL + Shift + R.

If you use a private browsing window, the page should also be loaded without using content from a cache.

**Comment by johmor52** [comment]
Thanks!
I got 1 error: Uncaught TypeError: Cannot read property 'addEventListener' of null
    at HTMLDocument.<anonymous> (bookmarks.min.js:9)
1
[syncmarks.log](https://github.com/Offerel/SyncMarks-Webapp/files/6126218/syncmarks.log)
 warning: DevTools failed to load SourceMap: Could not load content for chrome-extension://ikpmmbnjfndjmpmehlgeeinfkiaafdkf/assets/js/content.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
1 verbose: [DOM] Password forms should have (optionally hidden) username fields for accessibility: (More info: https://goo.gl/9p2vKq) <form action=​"/​SyncMarks/​index.php" method=​"POST">​…​</form>​
2 info: onMessage extension
ial.js:425 Clean the cache of the scraper (new onComplete event)
[syncmarks.log](https://github.com/Offerel/SyncMarks-Webapp/files/6126210/syncmarks.log)
I activated debug in config and attched.
Regards
Johan

**Comment by Offerel** [comment]
Maybe i have found something. I have added a commit [
c8b69d](https://github.com/Offerel/SyncMarks-Webapp/commit/c8b69d492d0f85289138b6cbc34671acebf38074) which should fix the issue. The issue should only occur, if there are no clients added, after a fresh installation. Can you please check if this solves the issue?

**Comment by johmor52** [comment]
THANK YOU!
Now I can open the menu.
Next step is to setup syncing between my computers. Windows 10, Debian with Firefox and Chrome and even edge.
Regards Johan

**Comment by johmor52** [comment]
Next step was not without problem. When I configure login from Firefox/Syncmark 1.17.9 it cant't save login if I'm not logged in in another tab. When I restart Firefox the log in Firefox/SyncMarks is:
2021-03-12 17:22:14 - Info: AddOn version: 1.17.9
2021-03-12 17:22:14 - Info: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0
2021-03-12 17:22:14 - Info: Current architecture: x86-64 | Current OS: win
2021-03-12 17:22:14 - Info: Initiate PHP startup sync
2021-03-12 17:22:14 - Info: Get list of clients.
2021-03-12 17:22:14 - Info: Get notifications for current client.
2021-03-12 17:22:14 - Info: Initiate startup sync
2021-03-12 17:22:14 - Error: Get list of notifications failed.
2021-03-12 17:22:15 - Info: There was a error retrieving the bookmarks from the server. The status response is: 401
2021-03-12 17:22:15 - Error: Get list of clients failed.:

If I try to save from the login screen, I got error. If I then open another tab and login I can save, but not export.
Is there any limit of how many bookmarks I can export? I have more than 2500.
I suppose this could be a new issue....
Regards Johan
