### ISSUE TITLE
User creation failed

### ISSUE THREAD

**Issue by johmor52** [Offerel/SyncMarks-Webapp#64]
Installed at web site.
Logged in as admin.
Changed password - OK
Tried to set an e-mail address:
Can't set e-mail for admin - no reaction clicking on EDIT.
[19-Mar-2021 10:32:31] - [notice] - admin - 31.208.210.52 - Change e-mail for admin
[19-Mar-2021 10:32:31] - [debug] - admin - 31.208.210.52 - UPDATE `users` SET `userMail` = 'info@jm-***.se' WHERE `userID` = 1;
[19-Mar-2021 10:32:31] - [error] - admin - 31.208.210.52 - DB update failed: SQLSTATE[HY000]: General error: 1 no such column: userMail

Tried to make new user.
Got on my screen:
Syncmarks - Error: User creation failed
- Nothing happened, no mail

Changed admin to johan@***to.se
- That worked.

If installed outside my own net I had to have an open tab logged in.

I managed to export from Firefox, but not from Edge and Chrome.
[syncmarks-new user.log](https://github.com/Offerel/SyncMarks-Webapp/files/6171689/syncmarks-new.user.log)

Problem is probably that there is no column: userMail

**Comment by johmor52** [comment]
I have tested 1.4.2 but I got some error.
I havn't found version 1.4.1 maybe that version had worked...
Here is my log from webapp and what came on screen trying to login:
[From Reader.txt](https://github.com/Offerel/SyncMarks-Webapp/files/6175801/From.Reader.txt)
[syncmarks.log](https://github.com/Offerel/SyncMarks-Webapp/files/6175802/syncmarks.log)

**Comment by Offerel** [comment]
Sorry, forgot to change the initial SQL to the current db version. You can see the new table in commit [8594057](https://github.com/Offerel/SyncMarks-Webapp/commit/859405764ef7cd09ab5ea343851ee61a4eefa3c6), or you replicate this by hand from the db_update_4.sql file. The result will be the same. I have seen, that 1.4.1 was not released yet. So i backported the changes in to the 1.4.1 branch. So the latest change is in commit [8594057](https://github.com/Offerel/SyncMarks-Webapp/commit/859405764ef7cd09ab5ea343851ee61a4eefa3c6)
